
stages:
    - build
    - test
#    - staging
    - production
    
image: maven:latest

variables:
    GIT_STRATEGY: clone
#    HEROKU_API_KEY: 516ca83e-0d6c-4149-8608-5ca8b521fd9f
#    HEROKU_STAGING_APP_NAME: heroku-gitlabenv-staging
#    HEROKU_PROD_APP_NAME: heroku-gitlabenv-prod


build-process:
    stage: build
    script:
        - mvn compile
    tags:
        - dalfcs_docker_kvm

test-process:
    stage: test
    script:
        - mvn test
    tags:
        - dalfcs_docker_kvm

#staging-process:
#    image: ruby:latest
#    stage: staging
#    tags:
#        - dalfcs_docker_kvm
#    script:
#        - apt-get update -qy
#        - apt-get install -y ruby-dev
#        - gem install dpl
#        - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_API_KEY
#    only:
#        - develop


production-process:
    stage: production
    image: ruby:2.6
    tags:
        - dalfcs_docker_kvm
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
