image: ubuntu:latest
variables:
    GIT_STRATEGY: clone

stages:
    - build
    - test
    - deploy


build:
    image: maven:3-jdk-8
    stage: build
    tags:
        - dalfcs_gitlab_docker_ci
    script:
        #- cd vehiclesharing
        - mvn clean package -DskipTests=true
    artifacts:
        paths:
            - vehiclesharing/target/*.jar
    only:
        refs:
            - shreya_dev
            


test:
    image: maven:3-jdk-8
    stage: test
    tags:
        - dalfcs_gitlab_docker_ci
    script:
        - mvn clean test
    artifacts:
        when: always
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml

    only:
        - main
        - shreya_dev


deploy:
    image: ruby:latest
    stage: deploy
    tags:
        - dalfcs_gitlab_docker_ci
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        #- cat ~/.ssh/id_rsa | pbcopy
        #

    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
        - shreya_dev