variables:
    GIT_STRATEGY: clone

build:
    stage: build
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn -f vehiclesharing/pom.xml clean install


test:
    stage: test
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn -f vehiclesharing/pom.xml clean test


deploy-test:
    stage: deploy
    tags:
        - dalfcs_gitlab_docker_ci
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main