variables:
    GIT_STRATEGY: clone

build:
    stage: build
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn clean install


test:
    stage: test
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn clean test


deploy-test:
    stage: deploy
    tags:
        - dalfcs_gitlab_docker_ci
    image: ruby:"ruby-2.3.6-with-yarn"
    script:
        - docker build --no-cache -t ${DOCKER_REGISTRY}/debian9-cunit
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main