image: ubuntu:latest
variables:
    GIT_STRATEGY: clone

stages:
    - build
    - test
    - deploy


build:
    image: maven:latest
    stage: build
    tags:
        - dalfcs_gitlab_docker_ci
    script:
        - mvn -f vehiclesharing/pom.xml clean package -DskipTests=true
    artifacts:
        paths:
            - target/*.jar
    only:
        refs:
            - shreya_dev


test:
    stage: test
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn clean test


deploy:
    image: ruby:latest
    stage: deploy
    tags:
        - dalfcs_gitlab_docker_ci
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -

    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
        - shreya_dev