
stages:
    - build
    - test
    - deploy
 

build:
    image: maven:3-jdk-11
    stage: build
    script:
        - mvn -f demo/pom.xml compile
    tags:
        - ugrad    
    #artifacts:
    # paths:
    #     - target/*.jar


test:
    image: maven:3-jdk-11
    stage: test
    script:
        - mvn -f demo/po.xml test
    artifacts:
    when: always
    tags:
        - ugrad
    # reports:
    #     junit:
    #         - target/surefire-reports/TEST-*.xml
    #         - target/failsafe-reports/TEST-*.xml

deploy-staging:
    image: ruby:latest
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_STAGING_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - develop


deploy-prod:
    image: ruby:latest
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - main
