variables:
    GIT_STRATEGY: clone

build:
    stage: build
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn -f vehiclesharing/pom.xml clean install


test:
    stage: test
    tags:
        - dalfcs_gitlab_docker_ci
    image: maven:latest
    script:
        - mvn -f vehiclesharing/pom.xm clean test


deploy-test:
    stage: deploy
    tags:
        - dalfcs_gitlab_docker_ci
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=ride-sharing --api-key=28b18150-7f5f-473e-99b1-f194a7c4cf65
    only:
        - main